version: "2"
services:
    nginx:
        build:
            context: .
            dockerfile: nginx.Dockerfile
        container_name: nginx
        command: nginx
        ports: [ "127.0.0.1:80:80" ]
        network_mode: "private_network"
        depends_on:
            - "jenkins"
        volumes:
            - cache:/data/nginx/cache
    jenkins:
        image: jenkins
        container_name: jenkins
        network_mode: "private_network"
        volumes:
            - data:/var/jenkins_home/
volumes:
  data:
    external: true
